### ISSUE TITLE
Console command is not working with source_profile

### ISSUE THREAD

**Issue by andrius-paurys** [aws-cloudformation/rain#108]
Maybe because of an update AWS CLI or AWS APIs? I just started trying out Rain, so can't say how it worked "before".
`aws-vault login assumed-role` works fine, so probably should not be an AWS permission issue.

```
$ rain console -p assumed-role --debug

DEBUG: Generating sign-in URL
DEBUG: Loading AWS config
DEBUG: Reloading AWS credentials
panic: invalid character '<' looking for beginning of value [recovered]
	panic: invalid character '<' looking for beginning of value

goroutine 1 [running]:
github.com/aws-cloudformation/rain/internal/cmd.execute.func1()
	github.com/aws-cloudformation/rain/internal/cmd/wrap.go:77 +0x1a8
panic({0x106498280, 0x1400062ea38})
	runtime/panic.go:884 +0x204
github.com/aws-cloudformation/rain/internal/cmd/console.Open(0x0, {0x1058400dc, 0xe}, {0x0, 0x0}, {0x0, 0x0})
	github.com/aws-cloudformation/rain/internal/cmd/console/util.go:20 +0x2b0
github.com/aws-cloudformation/rain/internal/cmd/console.glob..func1(0x106926aa0?, {0x14000948cf0?, 0x3?, 0x3?})
	github.com/aws-cloudformation/rain/internal/cmd/console/console.go:30 +0x70
github.com/spf13/cobra.(*Command).execute(0x106926aa0, {0x14000948cc0, 0x3, 0x3})
	github.com/spf13/cobra@v1.4.0/command.go:860 +0x4ac
github.com/spf13/cobra.(*Command).ExecuteC(0x106928120)
	github.com/spf13/cobra@v1.4.0/command.go:974 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.4.0/command.go:902
github.com/aws-cloudformation/rain/internal/cmd.execute(0x104f71594?)
	github.com/aws-cloudformation/rain/internal/cmd/wrap.go:86 +0x50
github.com/aws-cloudformation/rain/internal/cmd.Execute(0x6478f60?)
	github.com/aws-cloudformation/rain/internal/cmd/wrap.go:95 +0x1c
```

AWS config:
```
[profile iam-user-profile]
region = us-east-1
credential_process = aws-vault exec iam-user-profile --json

[profile assumed-role]
source_profile = iam-user-profile
region = us-east-1
role_arn = arn:aws:iam::xxxxxxxxxxxx:role/xxxx/xxxx
```

Versions:
```
$ rain --version
Rain v1.3.0 darwin/arm64
$ aws --version
aws-cli/2.10.3 Python/3.11.2 Darwin/21.6.0 source/arm64 prompt/off
```

Environment:
```
$ printenv | grep AWS
AWS_VAULT_KEYCHAIN_NAME=login
AWS_SDK_LOAD_CONFIG=1
```

**Comment by andrius-paurys** [comment]
I've tested this with a different identity and found that this is not a `credential_process` issue. I used IAM role with SSO auth as the main profile - `rain console` works fine on it. Another profile had that profile set as `source_profile` and I would get an "invalid character" error when trying to run `rain console` against this profile. I can run `rain info` successfully against both of these profiles.

**Comment by ericzbeard** [comment]
Making some progress on this. There is a call to signin.aws.amazon.com that results in a 400 that wasn't being caught, so we are trying to parse the HTML as if it's the valid JSON response.

**Comment by ericzbeard** [comment]
@andrius-paurys Is removing the 12-hour session duration from the console login going to be an issue? I'm hesitant to merge a "fix" that might make the experience worse for users that were not seeing this bug.

**Comment by andrius-paurys** [comment]
I can verify that I'm no longer seeing this issue in 1.3.3. Thanks!
