### ISSUE TITLE
awscli v2 credential store compatibility?

### ISSUE THREAD

**Issue by at0S** [aws-cloudformation/rain#13]
Hi, been using `rain` for a while, really useful tool, great work!

Here is my issue though, after upgrading to awscli v2 rain is unhappy, here is what I get when attempt a deploy passing `-p` to use profile:

`
$ rain deploy <template.yml <stack> -r <region>  -p <profile>
Unable to load AWS config
`

For the context, we're using  sso to fetch temporary credentials for accounts and v2 does help on that front, the invocation looks like:
`aws sso login --profile <profile>`

The temporary set of credentials ends up in the `~/.aws/sso/cache/<random>.json`  

Anything obvious I'm missing?

TY

**Comment by stilvoid** [comment]
Hi @at0S. Apologies for the delay in responding. Could you install `v0.8.0` and send me the output of `rain --debug info`? Thanks!

**Comment by at0S** [comment]
Hi @stilvoid, thanks for coming back on the topic! Here is what I'm getting:
```
$ aws sso login --profile <profile>
Attempting to automatically open the SSO authorization page in your default browser.
...
Successfully logged into Start URL: https://<company_name>-sso.awsapps.com/start

$ rain --debug info -p <profile>
DEBUG: Getting identity
DEBUG: Loading AWS config
DEBUG: Found cached credentials...
DEBUG: ...but there are none matching the requested profile
DEBUG: Trying default configs...
Loading AWS config ·˙.DEBUG: Invalid credentials: EC2RoleRequestError: no EC2 instance role found
caused by: RequestError: send request failed
caused by: Get "http://169.254.169.254/latest/meta-data/iam/security-credentials": dial tcp 169.254.169.254:80: connect: host is down
panic: Unable to find valid credentials [recovered]
        panic: Unable to find valid credentials

goroutine 1 [running]:
main.main.func1()
        /Users/taras.yermolenko/golang/pkg/mod/github.com/aws-cloudformation/rain@v0.8.2/main.go:33 +0x1aa
panic(0x1c0a1e0, 0x2fdda40)
        /usr/local/opt/go/libexec/src/runtime/panic.go:969 +0x166
github.com/aws-cloudformation/rain/client.loadConfig(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/taras.yermolenko/golang/pkg/mod/github.com/aws-cloudformation/rain@v0.8.2/client/common.go:125 +0xbd5
github.com/aws-cloudformation/rain/client.Config(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/taras.yermolenko/golang/pkg/mod/github.com/aws-cloudformation/rain@v0.8.2/client/common.go:133 +0x119
github.com/aws-cloudformation/rain/client/sts.getClient(0x0)
        /Users/taras.yermolenko/golang/pkg/mod/github.com/aws-cloudformation/rain@v0.8.2/client/sts/sts.go:11 +0x37
github.com/aws-cloudformation/rain/client/sts.GetCallerID(0x1e32579, 0x10, 0x0, 0x0, 0x0)
        /Users/taras.yermolenko/golang/pkg/mod/github.com/aws-cloudformation/rain@v0.8.2/client/sts/sts.go:16 +0x26
github.com/aws-cloudformation/rain/cmd.glob..func7(0x3994de0, 0xc00014a720, 0x0, 0x3)
        /Users/taras.yermolenko/golang/pkg/mod/github.com/aws-cloudformation/rain@v0.8.2/cmd/info.go:24 +0x87
github.com/spf13/cobra.(*Command).execute(0x3994de0, 0xc00014a690, 0x3, 0x3, 0x3994de0, 0xc00014a690)
        /Users/taras.yermolenko/golang/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:766 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x39946c0, 0x100784f, 0xc00010e058, 0x0)
        /Users/taras.yermolenko/golang/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:850 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/taras.yermolenko/golang/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:800
github.com/aws-cloudformation/rain/cmd.Execute()
        /Users/taras.yermolenko/golang/pkg/mod/github.com/aws-cloudformation/rain@v0.8.2/cmd/cmd.go:94 +0x2d
main.main()
        /Users/taras.yermolenko/golang/pkg/mod/github.com/aws-cloudformation/rain@v0.8.2/main.go:43 +0x44
```
Profiles are configured via the `~/.aws/config` and are in the following format:
```
[profile <profile>]
sso_start_url = https://<company_name>-sso.awsapps.com/start
sso_region = ap-southeast-2
sso_account_id = 012345678987
sso_role_name = <RoleName>
region = ap-southeast-2
```
TY

**Comment by stilvoid** [comment]
Hi @at0S - just an update on this. I've updated rain to the latest version of the AWS Go SDK but it seems like there is still no support for SSO there.

I will be monitoring the SDK for SSO support and will update if/when that appears.

**Comment by at0S** [comment]
Hey @stilvoid, no worries, thanks man

**Comment by andreasolund** [comment]
@stilvoid now that rain uses `github.com/aws/aws-sdk-go-v2 v1.2.0` will we get SSO support? 🙏

**Comment by at0S** [comment]
@andreasolund hey man, what exactly you have to do in order to make SSO happen with your `~/.aws/config` ?

**Comment by andreasolund** [comment]
> @andreasolund hey man, what exactly you have to do in order to make SSO happen with your `~/.aws/config` ?

I just installed the latest release of rain using Brew, defined the profile in the config file, then I logged in using the SSO command.

Example profile:

```
[profile my-dev-profile]
sso_start_url = https://my-sso-portal.awsapps.com/start
sso_region = us-east-1
sso_account_id = 123456789011
sso_role_name = readOnly
region = us-west-2
output = json
```

```
aws sso login --profile my-dev-profile
rain ls --profile my-dev-profile
```

**Comment by stilvoid** [comment]
Thanks @andreasolund! Is this working for you now too @at0S?

If so, please close the issue. If not, I'll set about creating myself an SSO setup to test with :)

**Comment by at0S** [comment]
@stilvoid, yes, I just tried what @andreasolund did and it works with rain v.1.1.2. Thanks guys!

**Comment by stilvoid** [comment]
Excellent news, thanks @andreasolund and @at0S !
