### ISSUE TITLE
rain ls --all fails if opt-in regions are disabled

### ISSUE THREAD

**Issue by benbridts** [aws-cloudformation/rain#47]
I would expect rain ls --all to skip regions that are not enabled, instead of stopping completely.

For opt-in regions, this should be possible by one of these changes in`https://github.com/aws-cloudformation/rain/blob/master/internal/aws/ec2/ec2.go#L18 :
- adding a filter so that ec2.DescribeRegions only returns those with `opt-in-status` as `opt-in-not-required` or `opted-in`
- Looking at the output of ec2.DescribeRegions and filtering out every region with `OptInStatus` `not-opted-in`

There is also something to be said to skip regions that are disabled by SCP or IAM policy (only when doing --all). To make this safe, probably with an extra --list-errors flag, so that a user can choose to only see errors instead of failing hard when it makes sense.
 
Output:
```
~$ rain ls --all --debug
panic: failed to list stacks: The security token included in the request is invalid [recovered]
	panic: failed to list stacks: The security token included in the request is invalid

goroutine 1 [running]:
github.com/aws-cloudformation/rain/internal/cmd.execute.func1(0xc0016c9f58)
	github.com/aws-cloudformation/rain/internal/cmd/wrap.go:77 +0x21d
panic(0x24179c0, 0xc001bbef70)
	runtime/panic.go:969 +0x1b9
github.com/aws-cloudformation/rain/internal/cmd/ls.glob..func1(0x315ac20, 0xc00000f1c0, 0x0, 0x2)
	github.com/aws-cloudformation/rain/internal/cmd/ls/ls.go:64 +0xe1f
github.com/spf13/cobra.(*Command).execute(0x315ac20, 0xc00000f1a0, 0x2, 0x2, 0x315ac20, 0xc00000f1a0)
	github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x315b160, 0x315b940, 0xc000167f48, 0x10467ea)
	github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.1/command.go:895
github.com/aws-cloudformation/rain/internal/cmd.execute(0x315b160, 0x0)
	github.com/aws-cloudformation/rain/internal/cmd/wrap.go:86 +0x65
github.com/aws-cloudformation/rain/internal/cmd.Execute(0x315b160)
	github.com/aws-cloudformation/rain/internal/cmd/wrap.go:95 +0x2b
main.main()
	command-line-arguments/main.go:23 +0x2d



~$ rain ls --region eu-south-1 --debug
panic: failed to list stacks: The security token included in the request is invalid [recovered]
	panic: failed to list stacks: The security token included in the request is invalid

goroutine 1 [running]:
github.com/aws-cloudformation/rain/internal/cmd.execute.func1(0xc001675f58)
	github.com/aws-cloudformation/rain/internal/cmd/wrap.go:77 +0x21d
panic(0x24179c0, 0xc001907540)
	runtime/panic.go:969 +0x1b9
github.com/aws-cloudformation/rain/internal/cmd/ls.glob..func1(0x315ac20, 0xc000440a50, 0x0, 0x3)
	github.com/aws-cloudformation/rain/internal/cmd/ls/ls.go:64 +0xe1f
github.com/spf13/cobra.(*Command).execute(0x315ac20, 0xc000440a20, 0x3, 0x3, 0x315ac20, 0xc000440a20)
	github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x315b160, 0x315b940, 0xc000187f48, 0x10467ea)
	github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.1.1/command.go:895
github.com/aws-cloudformation/rain/internal/cmd.execute(0x315b160, 0x0)
	github.com/aws-cloudformation/rain/internal/cmd/wrap.go:86 +0x65
github.com/aws-cloudformation/rain/internal/cmd.Execute(0x315b160)
	github.com/aws-cloudformation/rain/internal/cmd/wrap.go:95 +0x2b
main.main()
	command-line-arguments/main.go:23 +0x2d
```

**Comment by stilvoid** [comment]
Hey @benbridts, good catch! Should be an easy fix; I'll get this into the next release

**Comment by ericzbeard** [comment]
@benbridts is this still an issue? I can't repro it.
