### ISSUE TITLE
Artifact bucket creation is always interactive

### ISSUE THREAD

**Issue by romain-depres** [aws-cloudformation/rain#48]
`rain deploy --yes` prompts for a confirmation to create the artifact bucket. This is very confusing when running in a non-interactive environment such as a Kubernetes-based Jenkins agent as Rain only outputs the following: `no interactive terminal detected; try running rain in non-interactive mode`.

Running with `--debug` reveals the origin of the prompt:

```
panic: no interactive terminal detected; try running rain in non-interactive mode [recovered]
	panic: no interactive terminal detected; try running rain in non-interactive mode

goroutine 1 [running]:
github.com/aws-cloudformation/rain/internal/cmd.execute.func1(0xc000473f58)
	/__w/rain/rain/internal/cmd/wrap.go:77 +0x21d
panic(0x1816700, 0xc0003c2c60)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/aws-cloudformation/rain/internal/console.Ask(0xc0004ca690, 0x61, 0x5b, 0x19836d9)
	/__w/rain/rain/internal/console/console.go:90 +0x237
github.com/aws-cloudformation/rain/internal/console.Confirm(0x19d2d01, 0xc00004d560, 0x5b, 0x1)
	/__w/rain/rain/internal/console/console.go:117 +0x86
github.com/aws-cloudformation/rain/internal/aws/s3.RainBucket(0x0, 0x0)
	/__w/rain/rain/internal/aws/s3/s3.go:88 +0x2e5
github.com/aws-cloudformation/rain/internal/cmd/deploy.packageTemplate(0x7ffdda02af30, 0x25, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/__w/rain/rain/internal/cmd/deploy/util.go:177 +0xf4
github.com/aws-cloudformation/rain/internal/cmd/deploy.glob..func1(0x2556d40, 0xc0003ba700, 0x2, 0x7)
	/__w/rain/rain/internal/cmd/deploy/deploy.go:67 +0x255
github.com/spf13/cobra.(*Command).execute(0x2556d40, 0xc0003ba690, 0x7, 0x7, 0x2556d40, 0xc0003ba690)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x2557fa0, 0x2558780, 0xc0000f1f48, 0x446eaa)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/aws-cloudformation/rain/internal/cmd.execute(0x2557fa0, 0x0)
	/__w/rain/rain/internal/cmd/wrap.go:86 +0x65
github.com/aws-cloudformation/rain/internal/cmd.Execute(0x2557fa0)
	/__w/rain/rain/internal/cmd/wrap.go:95 +0x2b
main.main()
	/__w/rain/rain/cmd/rain/main.go:23 +0x2d
```

Version used: 1.1.1.

**Comment by stilvoid** [comment]
Good point! Fixed in 261249
