### ISSUE TITLE
`rain console --region=us-west-2` results in `runtime error: index out of range [1] with length 1`

### ISSUE THREAD

**Issue by jamesward** [aws-cloudformation/rain#495]
There is probably something wrong with my config or env vars but I'm not sure what.  Here is the debug error:
```
DEBUG: Generating URL
DEBUG: GetURI cloudformation, , 
DEBUG: Loading AWS config
panic: runtime error: index out of range [1] with length 1 [recovered]
	panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/aws-cloudformation/rain/internal/cmd.execute.func1()
	/__w/rain/rain/internal/cmd/wrap.go:77 +0x15e
panic({0x10c7020?, 0xc000042240?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
github.com/aws-cloudformation/rain/internal/aws/console.buildSessionString({0x0?, 0x0?})
	/__w/rain/rain/internal/aws/console/console.go:42 +0x3ec
github.com/aws-cloudformation/rain/internal/aws/console.getSigninToken({0x0?, 0x9?})
	/__w/rain/rain/internal/aws/console/console.go:61 +0x45
github.com/aws-cloudformation/rain/internal/aws/console.GetURI(0x0, {0x11341bc, 0xe}, {0x0, 0x0}, {0x0, 0x0})
	/__w/rain/rain/internal/aws/console/console.go:142 +0x2ae
github.com/aws-cloudformation/rain/internal/cmd/console.Open(0x0, 0x0, {0x11341bc, 0xe}, {0x0, 0x0}, {0x0, 0x0})
	/__w/rain/rain/internal/cmd/console/util.go:18 +0x185
github.com/aws-cloudformation/rain/internal/cmd/console.init.func1(0xc0000fca00?, {0xc000263ce0?, 0x4?, 0x1129787?})
	/__w/rain/rain/internal/cmd/console/console.go:31 +0x5c
github.com/spf13/cobra.(*Command).execute(0x2247c40, {0xc000263cc0, 0x2, 0x2})
	/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0x2246260)
	/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/aws-cloudformation/rain/internal/cmd.execute(0xc00004c0b8?)
	/__w/rain/rain/internal/cmd/wrap.go:86 +0x57
github.com/aws-cloudformation/rain/internal/cmd.Execute(0xc0000061c0?)
	/__w/rain/rain/internal/cmd/wrap.go:95 +0x13
main.main()
	/__w/rain/rain/cmd/rain/main.go:23 +0x1a
```

BTW, I downloaded and installed Rain 1.14.0, but the CLI reports:
```
Rain v1.13.0 linux/amd64
```

**Comment by ericzbeard** [comment]
Must be something with your aws config file, the command works fine for me.
